#!/bin/sh

if [ -z "$REPL_SLUG" ]; then
    echo "Error, you must run this script within Repl.it"
    exit 1
fi

readonly SLUG_DIR="$HOME/$REPL_SLUG"

cat > "$SLUG_DIR/replit.nix" <<EOF
{ pkgs }: {
        deps = [
                pkgs.clang_14
                pkgs.ccls
                pkgs.ncdu
                pkgs.hyperfine
                pkgs.tldr
                pkgs.gdb
                pkgs.gnumake
                pkgs.cmake
                pkgs.conan
                pkgs.eigen
                pkgs.meson
                pkgs.gsl
                pkgs.cairo
                pkgs.python310
                pkgs.python310Packages.pip
                pkgs.python310Packages.ipython
                pkgs.python310Packages.numpy
                pkgs.python310Packages.matplotlib
                pkgs.python310Packages.virtualenv
                pkgs.pandoc
                pkgs.valgrind
                pkgs.gnuplot
                pkgs.root
        ];
}
EOF

cat > "$HOME/.gdbinit" <<EOF
set disassembly-flavor intel
set print pretty on

layout src
break main
EOF

curl -s https://ziotom78.github.io/tnds-tomasi-notebooks/install_fmt_library > install_fmt_library
curl -s https://ziotom78.github.io/tnds-tomasi-notebooks/install_gplot++ > install_gplot++

chmod +x install_fmt_library install_gplot++

sed -i 's/ -g/ -std=c++20 -g/g' "$SLUG_DIR/Makefile"
