#!/bin/bash

# Copyright (c) 2020 Maurizio Tomasi
#
# This Bash script downloads the "fmt" C++ library and installs it in
# the current directory.

FMT_VERSION="11.0.0"

download_file() {
    filename="$1"
    dest="$2"

    if [ -z "$dest" ]; then
        dest=$filename
    fi

    destdir=$(dirname "$dest")
    if [ -n "$destdir" ]; then
        mkdir -p "$destdir"
    fi

    printf "Downloading file '%s' (version %s)\n" "$filename" "$FMT_VERSION"

    url="https://raw.githubusercontent.com/fmtlib/fmt/${FMT_VERSION}/$filename"

    if which curl >/dev/null 2>/dev/null; then
        curl -s "$url" > "$dest"
    elif which wget >/dev/null 2>/dev/null; then
        wget --quiet --output-document "$dest" "$url"
    else
        echo "Neither curl nor wget seem to be installed, aborting..."
        exit 1
    fi
}

echo "Going to download fmt library version ${FMT_VERSION} in current directory"
echo "Press ENTER to continue, or Ctrl+C to quit…"
read -s

for filename in fmt/args.h fmt/chrono.h fmt/color.h fmt/compile.h fmt/core.h fmt/format-inl.h fmt/format.h fmt/os.h fmt/ostream.h fmt/printf.h fmt/ranges.h fmt/std.h fmt/xchar.h; do
    download_file "include/$filename" "$filename"
done

#download_file src/format.cc format.cc

cat > fmtlib.h <<EOF
#pragma once

#define FMT_HEADER_ONLY
#include "fmt/format.h"
#include "fmt/color.h"
#include "fmt/os.h"
#include "fmt/ranges.h"
EOF

cat <<EOF
The library has been downloaded. To use it, include "fmtlib.h" in your C++ files:

    #include "fmtlib.h"
EOF
